stages:
  - verify
  - test
  - build
  - pages

.vet-tools: &vet-tools
  image: registry.gitlab.com/grauwoelfchen/portolan/rust-vet-tools:stable
  except:
    - tags

format:
  stage: verify
  <<: *vet-tools
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - mkdir -p .git/hooks
    - make verify:format

lint:
  stage: verify
  <<: *vet-tools
  before_script:
    - rustc --version
    - cargo --version
    - cargo clippy --version
  script:
    - mkdir -p .git/hooks
    - make verify:lint

test:
  stage: test
  <<: *vet-tools
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - mkdir -p .git/hooks
    - make test:all

coverage:
  stage: test
  <<: *vet-tools
  before_script:
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - mkdir -p .git/hooks
    - make clean
    - make coverage:all
  after_script:
    - cat target/coverage/index.json

build:
  stage: build
  image: registry.gitlab.com/grauwoelfchen/portolan/rust:stable
  before_script:
    - rustc --version
    - cargo --version
  script:
    - mkdir -p .git/hooks
    - make build
  cache:
    untracked: true
  only:
    - tags

pages:
  stage: pages
  image: grauwoelfchen/rust:stable
  before_script:
    - rustc --version
    - cargo --version
    - rustdoc --version
  script:
    - make doc
    - mkdir public
    - cp -R target/doc/* public/
    - cd public/ && ln -s 20min/index.html .
  artifacts:
    untracked: true
    paths:
      - public
  only:
    - trunk
