stages:
  - verify
  - test
  - build
  # - pages

.vet-tools: &vet-tools
  image: registry.gitlab.com/grauwoelfchen/portolan/rust-vet-tools:1.48.0-nightly
  except:
    - tags

format:
  stage: verify
  <<: *vet-tools
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - mkdir -p .git/hooks
    - make verify:format

lint:
  stage: verify
  <<: *vet-tools
  before_script:
    - rustc --version
    - cargo --version
    - cargo clippy --version
  script:
    - mkdir -p .git/hooks
    - make verify:lint

test:
  stage: test
  <<: *vet-tools
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - mkdir -p .git/hooks
    - make test:all
  after_script:
    - cat target/coverage/index.js

coverage:
  stage: test
  <<: *vet-tools
  before_script:
  variables:
    KCOV_PATH: kcov
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - mkdir -p .git/hooks
    - cargo clean --target-dir target/debug
    - make coverage
  after_script:
    - cat target/coverage/index.js

build:
  stage: build
  image: grauwoelfchen/rust:latest
  before_script:
    - rustc --version
    - cargo --version
  script:
    - mkdir -p .git/hooks
    - make build
  cache:
    untracked: true
  only:
    - tags

# pages:
#   stage: pages
#   image: grauwoelfchen/rust:nightly
#   before_script:
#     - rustc --version
#     - cargo --version
#     - rustdoc --version
#   script:
#     - make doc
#     - mkdir public
#     - cp -R target/doc/* public/
#     - cd public/ && ln -s 20min/index.html .
#   artifacts:
#     untracked: true
#     paths:
#       - public
#   only:
#     - trunk
