stages:
  - vet
  - test
  - build
  - pages

# stages
format:
  stage: vet
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - make vet:format
  except:
    - tags

lint:
  stage: vet
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - cargo clippy --version
  script:
    - make vet:lint
  except:
    - tags

test:
  stage: test
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - make test:all
  after_script:
    - cat target/coverage/index.json
  except:
    - tags

coverage:
  stage: test
  image: grauwoelfchen/rust-ci-tools:nightly
  variables:
    KCOV_PATH: kcov
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - cargo clean --target-dir target/debug
    - make coverage
  after_script:
    - cat target/coverage/index.json
  except:
    - tags

build:
  stage: build
  image: grauwoelfchen/rust:latest
  before_script:
    - rustc --version
    - cargo --version
  script:
    - make build
  cache:
    untracked: true
  only:
    - tags

# pages:
#   stage: pages
#   image: grauwoelfchen/rust:nightly
#   before_script:
#     - rustc --version
#     - cargo --version
#     - rustdoc --version
#   script:
#     - make doc
#     - mkdir public
#     - cp -R target/doc/* public/
#     - cd public/ && ln -s 20min/index.html .
#   artifacts:
#     untracked: true
#     paths:
#       - public
#   only:
#     - master
