stages:
  - test
  - build

test:
  stage: test
  image: rust:latest
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo test
  after_script:
    - kcov --include-path src target/coverage target/debug/20min-*
    - cat target/coverage/index.json
  except:
    - tags

build:
  stage: build
  image: rust:latest
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo build
  cache:
    untracked: true
  only:
    - tags
