stages:
  - test
  - build

test:
  stage: test
  image: rust:latest
  variables:
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y kcov
    - rustc --version
    - cargo --version
  script:
    - cargo test
  after_script:
    - kcov --include-path src --verify target/coverage target/debug/20min-*
    - cat target/coverage/index.json
  cache:
    untracked: true
    paths:
      - apt-cache
  except:
    - tags

build:
  stage: build
  image: rust:latest
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo build
  cache:
    untracked: true
  only:
    - tags
