#!/bin/bash
set -eu

if [ -n "${2:-}" ]; then
  kcov_cmd="${2}"
else
  kcov_dir="$(dirname $(readlink -f "${0}"))/kcov"
  kcov_cmd="${kcov_dir}/bin/kcov"
fi
echo "$kcov_cmd"

output_dir="$(pwd)/target/coverage"
target_dir="$(pwd)/target/debug"

target_name="${1}"
target_files=$(ls $target_dir/$target_name-* | grep -v '\.d$')
echo $target_files

for file in $target_files; do
  $kcov_cmd --verify --include-path=$(pwd)/src \
            "$output_dir" "$file"
done

grep -oE 'covered":"([0-9]*\.[0-9]*|[0-9]*)"' "$output_dir"/index.json | \
  grep -oE '[0-9]*\.[0-9]*|[0-9]*'
