#!/bin/bash
set -eu

kcov_dir="$(dirname $(readlink -f "${0}"))/kcov"
kcov_bin="${kcov_dir}/bin/kcov"

output_dir="$(pwd)/target/coverage"
target_dir="$(pwd)/target/debug"

target_name="${1}"
target_files=$(ls $target_dir/$target_name-* | grep -v '\.d$')
echo $target_files

for file in $target_files; do
  $kcov_bin --verify --include-path=$(pwd)/src \
            "$output_dir" "$file"
done

grep -oE 'covered":"([0-9]*\.[0-9]*|[0-9]*)"' "$output_dir"/index.json | \
  grep -oE '[0-9]*\.[0-9]*|[0-9]*'
